<?php

?>
<?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Shipping Method') ?> <span class="changelink"><span class="separator">|</span> <a
        href="#shipping_method"
        onclick="checkout.changeSection('opc-shipping_method'); return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="complete">
    <?php if ($this->getShippingMethod()): ?>
    <?php echo $this->getShippingDescription() ?>

    <?php $_excl = $this->getShippingPriceExclTax(); ?>
    <?php $_incl = $this->getShippingPriceInclTax(); ?>
    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
        <?php echo $_incl; ?>
        <?php else: ?>
        <?php echo $_excl; ?>
        <?php endif; ?>
    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
        <?php endif; ?>

    <?php else: ?>
    <?php echo $this->__('Shipping method has not been selected yet') ?>
    <?php endif; ?>
    <br>
    <?php $store = $this->getQuote()->getShippingAddress()->getStorePickup(); ?>
    <?php if($this->getShippingMethod() == SDT_StorePickup_Model_Pickup::SHIPPING_METHOD_CODE): ?>
        <?php echo Mage::app()->getStore($store)->getName() ?>
    <?php endif; ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Shipping Method') ?>
</dt>
<?php endif; ?>

